calendar: events: update calendar.event methods description;
bitrix-tools/b24-rest-docs pull request #59
Opened 2024-12-05 15:41 UTC by sgorshkov-bitrix

2024-12-06 11:27 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-add.md
> +```
Нет списка всех возможных ошибок. Пример: https://apidocs.bitrix24.ru/api-reference/sonet-group/scrum/backlog/tasks-api-scrum-backlog-add.html#vozmozhnye-kody-oshibok

Может есть ошибки связанные с доступом к каледарю, например?

2024-12-06 11:31 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-add.md
> +[`array`](../data-types.md) | Массив напоминаний о событии:
Тут по идее object, а не array

2024-12-06 11:33 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-delete.md
> +```
нет списка ошибок

2024-12-06 11:35 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-get-by-id.md
> +```
нет списка всех возможных ошибок

2024-12-06 11:36 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-get-nearest.md
> +```
нет списка всех возможных ошибок

2024-12-06 11:39 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-get.md
> +```
Нет списка всех возможных ошибок

2024-12-06 11:41 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-update.md
> +```
нет списка всех возможных ошибок

2024-12-06 11:44 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-get-by-id.md
> +
Здесь нужно описание всех возвращаемых полей.

2024-12-06 11:46 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-get-nearest.md
> +
Тут непонятно какие поля возвращаются для каждого события? Такие же как в методе getbyid?
Надо добавить в результат для одного из событий. Ну и описание всех возвращаемых тоже нужно.

2024-12-06 11:47 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-get.md
> +
Здесь тоже, добавить пример возвращаемого результата полностью для одного из событий. И описание полей.

2024-12-06 12:03 UTC, mp-bitrix-doc requested changes
Посмотрела, есть несколько вопросов. И не хватает:
- списков ошибок во всех методах
- описания возвращаемых полей в некоторых методах

2024-12-07 08:34 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-add.md
> +```
Добавлен список всех возможных ошибок по примеру.

2024-12-07 08:35 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-add.md
> +- UNTIL - дата окончания повторений. ||
Добавлены типы полей объекта тут и в методе update.

2024-12-07 08:36 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-add.md
> +[`array`](../data-types.md) | Массив напоминаний о событии:
Массив объектов напоминаний, в каждом из которых 2 поля `type` и `count`. Возможно это нужно как-то иначе описать?

2024-12-07 08:36 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-delete.md
> +```
Добавлен список всех возможных ошибок по примеру.

2024-12-07 08:37 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-get-by-id.md
> +```
Добавлен список всех возможных ошибок по примеру.

2024-12-07 08:44 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-get-nearest.md
> +```
Добавлен список всех возможных ошибок по примеру.

2024-12-07 08:44 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-get.md
> +```
Добавлен список всех возможных ошибок по примеру.

2024-12-07 08:45 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-update.md
> +```
Добавлен список всех возможных ошибок по примеру.

2024-12-07 13:49 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-get-by-id.md
> +
Добавлено описание всех полей события.

2024-12-07 13:49 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-get-nearest.md
> +
Добавлен пример возвращаемого события с описанием всех полей.

2024-12-07 13:50 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-get.md
> +
Добавлен пример возвращаемого события с описанием всех полей.

2024-12-16 08:30 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-add.md
> +[`array`](../data-types.md) | Массив напоминаний о событии:
А, поняла, тут может быть несколько напоминаний и каждое напоминание описывается объектом вида {type: 'min', count: 20}? Тогда да, массив объектов. Я поправлю сама в описании)

2024-12-16 08:45 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-get-by-id.md
> +[`string`](../data-types.md) | Статус участия в событии [Y\|N\|Q\|H] ||
Не хватает пояснения, какая буква какой статус означает

2024-12-16 08:46 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-event-get-by-id.md
> +- status [`string`](../data-types.md) - статус участника события [Y\|N\|Q\|H].||
Здесь не хватает того же пояснения, что и в поле MEETING_STATUS

2024-12-16 11:23 UTC, mp-bitrix-doc requested changes
Не хватает пояснений для статусов участия в событии [Y\|N\|Q\|H].

2024-12-16 11:25 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-get-by-id.md
> +- status [`string`](../data-types.md) - статус участника события [Y\|N\|Q\|H].||
Добавил пояснения.

2024-12-16 11:25 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-event-get-by-id.md
> +[`string`](../data-types.md) | Статус участия в событии [Y\|N\|Q\|H] ||
Добавил пояснения.

2024-12-16 11:38 UTC, mp-bitrix-doc approved these changes

2024-12-16 11:38 UTC, merged