calendar: settings: add description for calendar global and user settings;
bitrix-tools/b24-rest-docs pull request #65
Opened 2024-12-17 13:37 UTC by sgorshkov-bitrix

2024-12-18 08:24 UTC, mp-bitrix-doc commented on api-reference/calendar/calendar-settings-get.md
> +
А у этого метода нет ошибки доступа типа Access denied?
Метод может выполнить только администратор. А если выполнит другой пользователь, не админ, будет ошибка?

2024-12-18 09:21 UTC, mp-bitrix-doc requested changes
Посмотрела. Есть один вопрос.

2024-12-18 11:07 UTC, sgorshkov-bitrix commented on api-reference/calendar/calendar-settings-get.md
> +
Да, тут ошибка. Метод сейчас может быть вызван любым пользователем.
Поправил описание, добавил что изменять настройки может только администратор - это больше похоже на правду.

2024-12-19 06:26 UTC, mp-bitrix-doc approved these changes

2024-12-19 06:26 UTC, merged